name: personal-blog
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: alannapieralski/personal-blog
    image:
      registry_type: GHCR
      registry: ghcr.io
      repository: alannapieralski/personal-blog
      tag: latest
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
